name: flutter_animarker
description: Marker Geo-Animation solution for Google Maps.
version: 3.2.0-beta.3
homepage: https://github.com/gauris26/flutter_animarker
repository: https://github.com/gauris26/flutter_animarker
publish_to: https://pub.dev
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.0.4
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  import_sorter: ^4.4.2
  dart_test_matchers: ^0.1.0
  google_maps_flutter: ^2.0.3
  benchmark_harness: ^2.0.0
