name: flutter_animarker
description: Solution to move a Marker smoothly throught Google Maps in Flutter.
version: 0.1.1+1
homepage: https://github.com/gauris26/flutter_animarker
repository: https://github.com/gauris26/flutter_animarker

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.16.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
